### ISSUE TITLE
Fix WHILE GENERATION

### ISSUE THREAD

**Issue by herrBez** [StefanoMunari/FAC#12]

**Comment by herrBez** [comment]
Secondo me l'unico problema è nel caso in cui abbiamo:
while( FOGLIA ) 

il resto sembra funzionare senza problemi.

**Comment by herrBez** [comment]
The version of branch  "MODIFYTACASTNODE" seems to work --> Stefano please test it with other examples.

**Comment by StefanoMunari** [comment]
# REPORT  
* ex4.f (simple while): OK  
* ex6.f (simple while): OK  
* ex7.f (internal if): OK  
* ex26.f (nested while): ERROR (but the semantics seems fine)  
	* in /*SUM*/ h5 temporary variable is not declared but directly used (check it in printed C code)

## Notes:  
* lacks of type declaration (in C) for variables generates compile error (gcc). related to #9 
* problem with labels - it is not possible to directly declare temporary variables after a label in C
[Suggested solution](https://stackoverflow.com/questions/18496282/why-do-i-get-a-label-can-only-be-part-of-a-statement-and-a-declaration-is-not-a) 

## Proposal:  
PrintC prints to a ".c" file so we can directly compile the result instead of copying and pasting it   #

**Comment by herrBez** [comment]
ex26.f now works. In my opinion it functions. But I would keep the issue open in any evenience

**Comment by herrBez** [comment]
Maybe we can safely close this issue

**Comment by StefanoMunari** [comment]
I'll review tac_ast_node now to check any possible bug.
