### ISSUE TITLE
Fix IF-ELSE

### ISSUE THREAD

**Issue by StefanoMunari** [StefanoMunari/FAC#15]
TAC generation broken (segfault)

**Comment by herrBez** [comment]
The problem was due to:

1. Since we are skipping (after the warning message) something in the form `expr;` it leads to empty if or else body --> That caused the segfault, since we assume that the body is not empty.
2. skip is no more a keyword, it is treated as a variable 



Now in the MODIFYTACNODE you should find a solution (that should be checked and tested). But the principle is similar to Page 492 of the Dragon Book. It is the same as a bottom up construction

**Comment by StefanoMunari** [comment]
Seems fixed. Checked on ex20, 21, 22, 23, 24, 25, 26, 27.

**Comment by herrBez** [comment]
For me is also fixed
