### ISSUE TITLE
Solve all doxygen warnings / Comment all h files!!

### ISSUE THREAD

**Issue by herrBez** [StefanoMunari/FAC#26]

**Comment by herrBez** [comment]
Please Stefano @StefanoMunari, when you have time comment the tac_printer interface appropriately (in order to solve the doxygen warnings you have also to comment the external variables ecc..)

**Comment by StefanoMunari** [comment]
Ack

Stefano Munari

Il 06/giu/2017 08:53, "herrBez" <notifications@github.com> ha scritto:

Please Stefano @StefanoMunari <https://github.com/stefanomunari>, when you
have time comment the tac_printer interface appropriately (in order to
solve the doxygen warnings you have also to comment the external variables
ecc..)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/StefanoMunari/FAC/issues/26#issuecomment-306398436>,
or mute
the thread

**Comment by herrBez** [comment]
Now remains only the tac_printer warning and all the warnings related to bison and flex, which can we simply ignore...

**Comment by herrBez** [comment]
Now the parser.tab.h and parser.tab.c are no more considered by doxygen. The only thing to comment is tac_printer

**Comment by herrBez** [comment]
Please use both `@brief` to describe tprinter and tprinter_vtable (so the class list will be nice looking and can give an initial comprehension of the code). Use the `@details` tag to add details, if you need it

**Comment by StefanoMunari** [comment]
Complete. Waiting for a rebase ack for parser-review which contains the expected corrections.

**Comment by herrBez** [comment]
Ausgezeichnet! For me is :+1:
