### ISSUE TITLE
Documentare e sistemare (rifattorizzare se necessario???) il codice

### ISSUE THREAD

**Issue by herrBez** [StefanoMunari/FAC#7]
Documentare e sistemare (rifattorizzare se necessario???) il codice

**Comment by herrBez** [comment]
I was working on tac_ast_node and noted that the tac operations TAC_FRACT, TAC_BOOL, TAC_IF, TAC_WHILE and TAC_ELSE were not needed. I think that it is better to eliminate them .


**It is only a proposal** 
I do not know, but maybe we could (!) also consider the idea of removing the tac operation and use in the whole program the `op_t` type. So that we avoid risky asssignment during tac construction.

**Comment by StefanoMunari** [comment]
Ack. I'll review it and the other components starting from May 31th

**Comment by herrBez** [comment]
We should (?) also comment static functions, so that Satta can understand them (?)

**Comment by StefanoMunari** [comment]
In my opinion no, because these are not part of the "class" interface. They are only utility functions. If the professor has some doubts he could ask us through the forum, mail or directly at the exam. If some code parts are pretty obscure then it seems fine to comment them. Not using the doxygen style but only quick and short comments through the source code.
